title: Yessi Kenney
description: A collection of my GitHub projects

remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme


collections:
  projects:
    output: true
    permalink: /projects/:path/


    
