remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme

title: Yessi Kenney
description: A collection of my github projects
theme: minima

collections:
  projects:
    output: true
    permalink: /projects/:path/


    
